using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace UnityFramework.Editor
{
    /// <summary>
    /// Build Settings の enabled なシーンから <c>SceneId</c> enum + ToSceneName / ToBuildIndex 拡張メソッドを自動生成する。
    /// enum の値は Build Index に対応するため <c>(int)SceneId.X</c> でそのまま使える。
    ///
    /// 使い方:
    /// 1. File &gt; Build Settings からシーンを登録 (順序が Build Index になる)
    /// 2. Tools &gt; UnityFramework &gt; Generate Scene Enum を実行
    /// 3. 生成された <c>SceneId</c> を SceneController の enum オーバーロードで使う
    /// </summary>
    public static class SceneEnumGenerator
    {
        private const string MenuPath = "Tools/UnityFramework/Generate Scene Enum";
        private const string OutputPath = "Assets/Generated/UnityFramework/SceneIds.cs";
        private const string GeneratedNamespace = "UnityFramework.SceneManagement.Generated";
        private const string EnumName = "SceneId";

        [MenuItem(MenuPath)]
        public static void Generate()
        {
            var scenes = EditorBuildSettings.scenes;
            var entries = new List<(int buildIndex, string sceneName, string memberName)>();

            int currentBuildIndex = 0;
            foreach (var scene in scenes)
            {
                if (!scene.enabled) continue;
                var sceneName = Path.GetFileNameWithoutExtension(scene.path);
                if (string.IsNullOrEmpty(sceneName)) continue;
                var memberName = SanitizeIdentifier(sceneName);
                entries.Add((currentBuildIndex, sceneName, memberName));
                currentBuildIndex++;
            }

            if (entries.Count == 0)
            {
                EditorUtility.DisplayDialog(
                    "UnityFramework",
                    "Build Settings に enabled なシーンがありません。File > Build Settings からシーンを追加してください。",
                    "OK");
                return;
            }

            DeduplicateMemberNames(entries);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// このファイルは UnityFramework.Editor.SceneEnumGenerator により自動生成されました。");
            sb.AppendLine("// 手動編集しないでください。Build Settings 変更後は再生成してください。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Build Settings に登録された (enabled な) シーンの enum。");
            sb.AppendLine("    /// enum の値は Build Index に一致する。");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public enum {EnumName}");
            sb.AppendLine("    {");
            foreach (var entry in entries)
            {
                sb.AppendLine($"        {entry.memberName} = {entry.buildIndex},");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public static class {EnumName}Extensions");
            sb.AppendLine("    {");
            sb.AppendLine($"        /// <summary>enum をシーン名 (Build Settings 登録名) に変換する。</summary>");
            sb.AppendLine($"        public static string ToSceneName(this {EnumName} id) => id switch");
            sb.AppendLine("        {");
            foreach (var entry in entries)
            {
                var escaped = entry.sceneName.Replace("\\", "\\\\").Replace("\"", "\\\"");
                sb.AppendLine($"            {EnumName}.{entry.memberName} => \"{escaped}\",");
            }
            sb.AppendLine("            _ => null,");
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>enum を Build Index に変換する (値そのまま)。</summary>");
            sb.AppendLine($"        public static int ToBuildIndex(this {EnumName} id) => (int)id;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var dir = Path.GetDirectoryName(OutputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }
            File.WriteAllText(OutputPath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"[SceneEnumGenerator] 生成完了: {OutputPath} ({entries.Count} シーン)");
        }

        private static void DeduplicateMemberNames(List<(int buildIndex, string sceneName, string memberName)> entries)
        {
            var counts = new Dictionary<string, int>();
            for (int i = 0; i < entries.Count; i++)
            {
                var name = entries[i].memberName;
                if (counts.TryGetValue(name, out var c))
                {
                    counts[name] = c + 1;
                    entries[i] = (entries[i].buildIndex, entries[i].sceneName, $"{name}_{c}");
                }
                else
                {
                    counts[name] = 1;
                }
            }
        }

        private static string SanitizeIdentifier(string input)
        {
            if (string.IsNullOrEmpty(input)) return "_";
            var s = Regex.Replace(input, "[^a-zA-Z0-9_]", "_");
            if (char.IsDigit(s[0])) s = "_" + s;
            return s;
        }
    }
}
