using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace UnityFramework.Editor
{
    /// <summary>
    /// Addressables のラベル別にサウンド ID 用 enum + アドレス変換マップを生成するエディタツール。
    /// 例: ラベル "BGM" の Addressable 群から <c>BgmId</c> enum と <c>BgmIdExtensions.ToAddress()</c> を生成。
    ///
    /// 使い方:
    /// 1. Addressables Groups で各サウンドアセットに "BGM" / "SE" / "Voice" ラベルを付与する
    /// 2. Tools &gt; UnityFramework &gt; Generate Sound Enums を実行
    /// 3. 生成された enum を SoundController.PlayBGMAsync / PlaySE で型安全に渡す
    /// </summary>
    public static class SoundEnumGenerator
    {
        private const string MenuPath = "Tools/UnityFramework/Generate Sound Enums";
        private const string OutputPath = "Assets/Generated/UnityFramework/SoundIds.cs";
        private const string GeneratedNamespace = "UnityFramework.Audio.Generated";

        /// <summary>
        /// 生成対象の Addressables ラベルと、出力する enum 名のマッピング。
        /// プロジェクト固有のラベルを追加する場合は、このディクショナリを編集する。
        /// </summary>
        private static readonly Dictionary<string, string> LabelToEnumName = new Dictionary<string, string>
        {
            { "BGM", "BgmId" },
            { "SE", "SeId" },
            { "Voice", "VoiceId" },
        };

        [MenuItem(MenuPath)]
        public static void Generate()
        {
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                EditorUtility.DisplayDialog(
                    "UnityFramework",
                    "Addressables 設定が見つかりません。Window > Asset Management > Addressables > Groups から初期化してください。",
                    "OK");
                return;
            }

            var byLabel = new Dictionary<string, List<AddressableAssetEntry>>();
            foreach (var group in settings.groups)
            {
                if (group == null) continue;
                foreach (var entry in group.entries)
                {
                    foreach (var label in entry.labels)
                    {
                        if (!LabelToEnumName.ContainsKey(label)) continue;
                        if (!byLabel.TryGetValue(label, out var list))
                        {
                            list = new List<AddressableAssetEntry>();
                            byLabel[label] = list;
                        }
                        list.Add(entry);
                    }
                }
            }

            if (byLabel.Count == 0)
            {
                EditorUtility.DisplayDialog(
                    "UnityFramework",
                    $"対象ラベル ({string.Join(", ", LabelToEnumName.Keys)}) に該当する Addressable エントリが見つかりません。",
                    "OK");
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// このファイルは UnityFramework.Editor.SoundEnumGenerator により自動生成されました。");
            sb.AppendLine("// 手動編集しないでください。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");

            bool first = true;
            foreach (var kv in byLabel)
            {
                if (!first) sb.AppendLine();
                first = false;
                AppendEnumAndExtensions(sb, LabelToEnumName[kv.Key], kv.Value);
            }

            sb.AppendLine("}");

            var dir = Path.GetDirectoryName(OutputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }
            File.WriteAllText(OutputPath, sb.ToString());
            AssetDatabase.Refresh();

            Debug.Log($"[SoundEnumGenerator] 生成完了: {OutputPath}");
        }

        private static void AppendEnumAndExtensions(StringBuilder sb, string enumName, List<AddressableAssetEntry> entries)
        {
            entries.Sort((a, b) => string.CompareOrdinal(a.address, b.address));

            var pairs = new List<(string member, string address)>();
            foreach (var entry in entries)
            {
                var member = SanitizeIdentifier(Path.GetFileNameWithoutExtension(entry.address));
                pairs.Add((member, entry.address));
            }
            DeduplicateMemberNames(pairs);

            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");
            foreach (var p in pairs)
            {
                sb.AppendLine($"        {p.member},");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public static class {enumName}Extensions");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static string ToAddress(this {enumName} id) => id switch");
            sb.AppendLine("        {");
            foreach (var p in pairs)
            {
                var escapedAddress = p.address.Replace("\\", "\\\\").Replace("\"", "\\\"");
                sb.AppendLine($"            {enumName}.{p.member} => \"{escapedAddress}\",");
            }
            sb.AppendLine("            _ => null,");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
        }

        private static void DeduplicateMemberNames(List<(string member, string address)> pairs)
        {
            var counts = new Dictionary<string, int>();
            for (int i = 0; i < pairs.Count; i++)
            {
                var name = pairs[i].member;
                if (counts.TryGetValue(name, out var c))
                {
                    counts[name] = c + 1;
                    pairs[i] = ($"{name}_{c}", pairs[i].address);
                }
                else
                {
                    counts[name] = 1;
                }
            }
        }

        private static string SanitizeIdentifier(string input)
        {
            if (string.IsNullOrEmpty(input)) return "_";
            var s = Regex.Replace(input, "[^a-zA-Z0-9_]", "_");
            if (char.IsDigit(s[0])) s = "_" + s;
            return s;
        }
    }
}
